version: '3.8'
services:
  postgres:
    image: postgres:shop
    container_name: backend_shop
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=shop

volumes:
  postgres:
    name: backend_shop
