version: '3.8'
services:
  app:
    container_name: backend_shop
    image: backend_shop
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3030:3030
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    restart: unless-stopped
    environment:
      - NODE_ENV=dev
      - PORT=3030
      - DATABASE_URL=shop
  postgres:
    image: postgres:shop
    container_name: postgres:shop
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=shop
volumes:
  postgres:
    name: backend_shop
